
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconXSelector = "fhi-icon-x";

@customElement(FhiIconXSelector)
export class FhiIconX extends LitElement {
  @property({ type: String }) color: string = "currentcolor";

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.size}" height="${this.size}" fill="${this.color}"><path d="M17.47 5.47a.75.75 0 1 1 1.06 1.06L13.06 12l5.47 5.47.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052L12 13.06l-5.47 5.47a.75.75 0 1 1-1.06-1.06L10.94 12 5.47 6.53l-.052-.056a.75.75 0 0 1 1.056-1.056l.056.052L12 10.94z"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
