
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconChevronUpSelector = "fhi-icon-chevron-up";

@customElement(FhiIconChevronUpSelector)
export class FhiIconChevronUp extends LitElement {
  @property({ type: String }) color: string = "currentcolor";

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.size}" height="${this.size}" fill="${this.color}"><path d="M11.526 8.418a.75.75 0 0 1 1.004.052l6 6 .052.056a.75.75 0 0 1-1.056 1.056l-.056-.052L12 10.06l-5.47 5.47a.75.75 0 1 1-1.06-1.06l6-6z"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
