
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconArrowUpLeftSelector = "fhi-icon-arrow-up-left";

@customElement(FhiIconArrowUpLeftSelector)
export class FhiIconArrowUpLeft extends LitElement {
  @property({ type: String }) color: string = "currentcolor";

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.size}" height="${this.size}" fill="${this.color}"><path d="M6.25 17V7A.75.75 0 0 1 7 6.25h10a.75.75 0 0 1 0 1.5H8.81l8.72 8.72.052.056a.75.75 0 0 1-1.056 1.056l-.056-.052-8.72-8.72V17a.75.75 0 0 1-1.5 0"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
