
/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

export const FhiIconUserSelector = "fhi-icon-user";

@customElement(FhiIconUserSelector)
export class FhiIconUser extends LitElement {
  @property({ type: String }) color: string = "currentcolor";

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${this.size}" height="${this.size}" fill="${this.color}"><path d="M16.25 8a4.25 4.25 0 1 0-8.5 0 4.25 4.25 0 0 0 8.5 0m1.5 0a5.74 5.74 0 0 1-2.63 4.828 8.75 8.75 0 0 1 3.068 1.985A8.75 8.75 0 0 1 20.75 21a.75.75 0 0 1-1.5 0 7.25 7.25 0 0 0-6.89-7.241L12 13.75A7.25 7.25 0 0 0 4.75 21a.75.75 0 0 1-1.5 0 8.75 8.75 0 0 1 2.563-6.187 8.75 8.75 0 0 1 3.066-1.985A5.75 5.75 0 1 1 17.75 8"/></svg>
    `;
  }
      
  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
  }
