/*
  This file is auto-generated by generate-icon-components.js. Do not edit it manually.
*/
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

export const FhiIconLink2Selector = 'fhi-icon-link-2';

@customElement(FhiIconLink2Selector)
export class FhiIconLink2 extends LitElement {
  @property({ type: String }) color: string = 'currentcolor';

  @property({ type: Number }) size: number = 24;

  render() {
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="${this.size}"
        height="${this.size}"
        fill="${this.color}"
      >
        <path
          d="M9 6.25a.75.75 0 0 1 0 1.5H7a4.25 4.25 0 0 0 0 8.5h2a.75.75 0 0 1 0 1.5H7a5.75 5.75 0 0 1 0-11.5zm8 0a5.75 5.75 0 0 1 .285 11.493L17 17.75h-2a.75.75 0 0 1 0-1.5h2a4.25 4.25 0 0 0 .21-8.495L17 7.75h-2a.75.75 0 0 1 0-1.5zm-1 5a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5z"
        />
      </svg>
    `;
  }

  static styles = css`
    :host {
      display: flex;
      max-height: min-content;
      max-width: min-content;
    }
  `;
}
