name: Publish PR to GitHub Packages (Test 2)

permissions:
  contents: read
  issues: write
  packages: write

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master]

env: 
  PACKAGE_SCOPE: "@fhidev"
  PACKAGE_NAME: "designsystem-pull-request-${{ github.event.pull_request.number }}"
  PACKAGE_VERSION: "0.0.${{ github.run_number }}"

jobs:
  publish-github-package:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        working-directory: ./packages/fhi-designsystem
        run: pnpm lint

      - name: Build
        working-directory: ./packages/fhi-designsystem
        run: pnpm build:github

      - name: Update package name for staging
        working-directory: ./packages/fhi-designsystem/dist/github
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_RUN_NUMBER: ${{ github.run_number }}
        run: |
          jq --arg name "${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}" \
            --arg version "${{ env.PACKAGE_VERSION }}" \
            '.name = $name | .version = $version' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Delete staging package if it already exists
        env:
            ORG: FHIDev
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
            curl -X DELETE \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/orgs/$ORG/packages/npm/${{ env.PACKAGE_NAME }} || true


      - name: Configure npm for GitHub Packages
        working-directory: ./packages/fhi-designsystem/dist/github
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "${{ env.PACKAGE_SCOPE }}:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: Publish package to GitHub Packages
        working-directory: ./packages/fhi-designsystem/dist/github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

  comment_on_pr:
    needs: publish-github-package
    runs-on: ubuntu-latest
    environment: development
    if: github.event.action != 'closed'
    steps:
      - name: Comment on PR with package info
        uses: actions/github-script@v8
        with:
          github-token: ${{secrets.REPO_GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Staging NPM Package published:** \`@fhidev/designsystem-pull-request-${{ github.event.pull_request.number }}@0.0.${{ github.run_number }}\`
            [View on GitHub Packages](https://github.com/FHIDev/${{ github.event.repository.name }}/pkgs/npm/${{ env.PACKAGE_NAME }})`
                  })