name: Pull Request Guard

permissions:
  contents: write
  id-token: write

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest-4xlarge
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: cd packages/fhi-designsystem; pnpm lint

      - name: Build
        run: cd packages/fhi-designsystem; pnpm build

      - name: Prepare Testing Environment
        run: cd packages/fhi-designsystem; pnpm exec playwright install --with-deps

      - name: Test
        run: cd packages/fhi-designsystem; pnpm test
