name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - button

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Guard - Commit message should have prefix
        id: guard_commit_message
        run: |
          LAST_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: \"$LAST_COMMIT_MESSAGE\""
          if [[ "$LAST_COMMIT_MESSAGE" != feat:\ * && "$LAST_COMMIT_MESSAGE" != fix:\ * && "$LAST_COMMIT_MESSAGE" != chore:\ * && "$LAST_COMMIT_MESSAGE" != docs:\ * ]]; then
            echo "ERROR: Prefix 'feat: ', 'fix: ', 'docs: ' or 'chore: ' is missing from the commit message."
            exit 1
          fi
        shell: bash

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: cd packages/fhi-designsystem; pnpm lint

      - name: Build
        run: cd packages/fhi-designsystem; pnpm build

      - name: Prepare Testing Environment
        run: cd packages/fhi-designsystem; pnpm exec playwright install --with-deps

      - name: Test
        run: cd packages/fhi-designsystem; pnpm test

      - name: Build Storybook
        run: cd packages/fhi-designsystem; pnpm storybook:build

      - name: Deploy Storybook
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STORYBOOK_TEST }}
          action: 'upload'
          app_location: 'packages/fhi-designsystem/storybook-static'
          skip_app_build: true
